### PR TITLE
Remove all ocurrences of "jude"

### PR DESCRIPTION
**Pull request by svenXY**
Hi,

I was a quite surprised to get a suggestion "volljude", which - in my opinion - is a racist Nazi term.
Therefore I'd suggest to remove all occurrences of "jude" from the german wordlist.

### CODE REVIEW

**Comment by martinhoefling** [comment]
Hi Sven, thank you for reporting this! That's definitely an inacceptable term in the wordlist. I have check where the the wordlist is from and will remove the entire list if there are doubts.

**Comment by martinhoefling** [comment]
@svenXY I checked the list for some more terms and removed it after some more findings.

**Comment by svenXY** [comment]
sorry to see that you had to completely remove support for german, but I understand your concern.

https://sourceforge.net/projects/germandict/files/ might have a wordlist that could be used instead, but I didn't check if it has the same problems...

**Comment by martinhoefling** [comment]
From the readme of that project

```
How was it made?
¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
The short answer is: basically by running Hunspell on a huge corpus. For 
a somewhat longer version, please refer to "Quellen und Methoden.txt" 
(in German) for now. I'm in the process of writing a Medium 
article with more details on how I made this.
```
from the mentioned `"Quellen und Methoden.txt"`

```
...
(1) XML-Dump der deutschen Wikipedia:
https://dumps.wikimedia.org/dewiki/latest/, genauer die Datei dewiki-latest-pages-articles.xml.bz2
(2) Ein paar mˆglichst lange Texte von
http://deutsch.bestpornstories.com
(f¸r Umgangs- und Vulg‰rsprache)
(3) Textversion von OpenThesaurus:
https://www.openthesaurus.de/about/download
(mit Einverst‰ndnis von Daniel Naber, der mich ¸berhaupt auf diese Idee gebracht hat)
(4) Allerhand eigene Texte, die sich bei mir angesammelt hatten: Briefe, Texte aus dem Studium etc.
...
```

(2) and (4) don't sound like a good source for such a list and I can imagine that the previous list also was generated by parsing German literature from the first half of the last century.

I'm happy to add support for any language if a curated list in the public domain exists.

**Pull request merged**
